# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fb7a226d00e4ae3b1b5baa17471ee901608508dbf09f8b76286254a75c1a52757f8300ee02c09533549d884b72ebdee99f34eb54c5ededa42f1c69d96114fcf

test:
  secret_key_base: b9a0a891ce5e424cd0b22787f16025b91b84aa1362dc0f71db2005083267f1efce31400a1bf0a33905f615008ab0c54ddf7bfeda64e9ddd4460467ac9f9521c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
